name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: xcodebuild build -scheme SwiftConfettiView -destination 'generic/platform=iOS Simulator'

    - name: Test
      run: xcodebuild test -scheme SwiftConfettiView -destination 'platform=iOS Simulator,name=iPhone 15'

  spm:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - name: Build (SPM)
      run: xcodebuild build -scheme SwiftConfettiView -destination 'generic/platform=iOS Simulator'
